### ISSUE TITLE
SampleIDs not in tree order on heatmap

### ISSUE THREAD

**Issue by rbrauning** [AgResearch/KGD#16]
When using heatmaply sampleIDs appear in perfect consecutive order (1, 2, 3, 4) on the axis. This is in contrast to the default non-plotly output that's more like 8, 39, 120, 5.

**Comment by tpbilton** [comment]
This has now been sort in commit #19. There was a bug in the heatmaply package which is fixed in version 0.15.0. This issue can be closed.
