### ISSUE TITLE
Excel misinterprets CSV as SYLK file

### ISSUE THREAD

**Issue by rbrauning** [AgResearch/KGD#20]
When trying to open the csv file in Excel which contains the GRM in long format I got the following error: `Excel detected that *-long.csv is a SYLK file but cannot load it`
One can click through a couple of error messages to open the file. Annoying.
Looks like Excel interprets csv files where the first record starts with "ID" as SYLK file 👎 

The work-around is to change "ID" to something else, e.g. "id".

**Comment by doddsk** [comment]
Names are now id1 and id2 (lower case).
Changed in v0.5.1
