### ISSUE TITLE
writeG crashes, where there are 2 different negative controls , everything else replicated twice 

### ISSUE THREAD

**Issue by afmcc** [AgResearch/KGD#30]
received the error below at the end of the KGD run, analysing a set of 26 samples, 
each replicated twice , with two negative controls "GBSNEG1" and "GBSNEG2" each replicated 
only once.  Workaround was to rename both controls to GBSNEG1 so replication
matched the rest of the samples.

Error in data.frame(..., check.names = FALSE) :
  arguments imply differing number of rows: 27, 26
Calls: writeG -> cbind -> cbind -> data.frame
Execution halted

**Comment by doddsk** [comment]
Problem not with merging replicated results. 
Problem was that the PCA needed to drop a sample with missing relatedness values (presumably very low call rate), but the writeG function did not recognize that.
This has been resolved.
Thanks for pointing it out.
