### ISSUE TITLE
Change ep default for writeVCF to 0.001

### ISSUE THREAD

**Issue by rbrauning** [AgResearch/KGD#31]
I suggest changing the ep default from ep=0 to ep=0.001 to reflect the fact that sequencing results are not perfect. Code and documentation would need updating.
https://github.com/AgResearch/KGD/blob/832e08d5dba56fd1de472867c6bde78afc2d54b2/GBS-Chip-Gmatrix.R#L1070

**Comment by doddsk** [comment]
Changed in v0.8.2
