### ISSUE TITLE
Number of SNPs for determination of relatedness

### ISSUE THREAD

**Issue by aadamk** [AgResearch/KGD#36]
Hello,
I have data from Illumina's ForenSeq kit (https://www.illumina.com/products/by-type/sequencing-kits/library-prep-kits/forenseq-dna-signature.html), which includes <100 identity-informative SNPs with high allele frequencies (0.3 or greater). 
Is it possible to obtain accurate estimates of relatedness between two samples with information on approximately 70-80 SNPs?

**Comment by doddsk** [comment]
Firstly, KGD is designed to cope with low-depth sequencing reads, normally with many 1000's SNPs. Without looking at the details of the ForenSeq product it will likely produce heihg-depth genotype results.

To answer your question, <100 SNPs won't produce very accurate relatedness estimates. For example, Fig 4 of [Dodds _et _al._, (2015)](https://doi.org/10.1186/s12864-015-2252-3) shows that the sd for a parent-offspring relatedness estimate when MAF=0.3 and using 1000 'independent' SNPs is about 0.06. This is probably about as low as would be useful (depends on the situation). Dropping to 80 SNPs would increase the sd by sqrt(1000/80) = 3.5, i.e. an sd of about 0.2.

**Comment by aadamk** [comment]
Thank you for the insight.
