### ISSUE TITLE
Error sourcing GBS-Chip-Gmatrix.R

### ISSUE THREAD

**Issue by balathumma10** [AgResearch/KGD#43]

**Comment by doddsk** [comment]
Hi,
You may have loaded a package that has defined _maf_ (probably as a function) and KGD cannot override that (from within the function).  I have already included a small section on this for the next update of the documentation:

> Some of the structures defined in the KGD software may be incompatible with those defined in some packages. A known issue is that adegenet defines an alleles function while KGD defines an alleles matrix. Therefore adegenet should not be loaded until at least after using KGD to read the datafile.

If you find that it is a incompatibility with another package please let me know and I will note it in the documentation.

**Comment by balathumma10** [comment]
It seems that is the case. When I removed all the objects and re started R it started working. Thank you.
